ERP Spec revisions
allthings/developers pull request #6
Opened 2018-06-12 12:17 UTC by adieuadieu

Initial changes to the spec as we (@davgun29 & @chrisallthings) discussed in our meeting 2018-06-12.

Items which require follow-up:

- [ ] checkIns.csv has been renamed
- [ ] checkIns.csv's `tenantId` field is no longer valid. E.g. we also need registrationCodeId and companyId, or a way to simplify this
- [ ] what are all the fields for the tenants.csv?
- [ ] what are all the fields for the companies.csv?
- [ ] propose renaming `manifest.json` to something else like `settings.json` while we're at it.

Feel free to add/make additional changes to this branch.

2018-06-14 13:27 UTC, chrisallthings commented on erp-data-exchange-specification.md
>      1.  [propertyTeams.csv](#propertyteamscsv)
Should be renamed to checkIns.csv, right?

2018-06-14 13:28 UTC, chrisallthings commented on erp-data-exchange-specification.md
>      1.  [tenantCheckIns.csv](#tenantcheckinscsv)
this should be renamed into checkIns.csv and linked to the right capter

2018-06-14 13:31 UTC, chrisallthings commented on erp-data-exchange-specification.md
> +[_utilisationPeriods.csv_](#utilisationperiodscsv), [_tenantCheckIns.csv_](#tenantcheckinscsv), [registrationCodes.csv_](#registrationcodescsv), [_tenants.csv_](#tenantscsv), [companies.csv_](#compan
also here the tenantCheckIns.csv should be renamed in to checkIns.csv

2018-08-06 10:09 UTC, immerwiederchia reviewed
Great thx. I think this looks good for what we know now. I will go through the details now.

2018-08-06 10:15 UTC, immerwiederchia approved these changes

2018-08-06 10:20 UTC, chrisallthings commented
Hi Marco, 

I agree with all of your comments. From my point of view the biggest questions are those two: 
- [ ] what are all the fields for the tenants.csv?
- [ ] what are all the fields for the companies.csv?

But we can't answer them yet and we have to wait for team orange for the final concept of the company data modell.

2018-08-06 10:41 UTC, chrisallthings commented
@adieuadieu I just realized that i missed one point of your comment.  

- [x] checkIns.csv's `tenantId` field is no longer valid. E.g. we also need registrationCodeId and companyId, or a way to simplify this

I checked this and did some changes to the documentation (see checkIns.csv and registrationCodes.csv) I think this should work now. Right? 

RegistrationCodes would be optional in this model but if one wants to use a registrationCode for serveral Units and let's say one company. In the checkIns.csv all the fields are required - if not we wouldn't know what company can use what registrationCode. Right?

2018-08-06 12:53 UTC, iamn1ck requested changes

2018-08-06 12:53 UTC, iamn1ck commented on erp-data-exchange-specification.md
> +importType,residentId,name
missing a column here

2018-08-27 08:33 UTC, adashst commented on erp-data-exchange-specification.md
> +The `registrationCodes.csv` file describes registration codes for one or more utilizationPeriods. It contains the registrationCode and the reseidentId of those entities that are checked into these ut
small Typo: reseidentId -> residentId

2018-08-27 08:35 UTC, adashst commented on erp-data-exchange-specification.md
> +| **id**               | [UUID](#uuid-type)          | UUID to identify registrationCode |
1) shouldn't id be: registrationCodeId
2) residentId is missing

2018-08-27 08:35 UTC, adashst commented on erp-data-exchange-specification.md
> +importType,id,residentId,registrationCode
id -> registrationCodeId

2018-08-27 08:38 UTC, adashst commented on erp-data-exchange-specification.md
> +The `tenants.csv` file describes a tenant.
Shouldn't we be consistent in terms of why is the file called `tenants.csv` when it contains residentIds?

2018-08-27 08:39 UTC, adashst commented on erp-data-exchange-specification.md
> +| **id**               | [UUID](#uuid-type)          | Your UUID for the company |
id -> companyId?

2018-08-27 08:39 UTC, adashst commented on erp-data-exchange-specification.md
> +importType,residentId,name
importType,companyId,name,email

2018-08-27 08:44 UTC, adashst commented on erp-data-exchange-specification.md
> +insert,41f93044-e050-4a33-9e52-ebdada55f9a7,West & Smith, Inc., manager@ws.com
Strings that include commas should be enclosed in " 
like:
insert,41f93044-e050-4a33-9e52-ebdada55f9a7,"West & Smith, Inc.", manager@ws.com

2018-08-27 09:09 UTC, adashst reviewed
Did some changes though not being 100% sure about how the structure should be.

2018-08-27 09:11 UTC, iamn1ck approved these changes

2020-06-04 17:06 UTC, closed without merging